#!/usr/bin/env node
// dev-env: project a single local-dev master file into each app/package .env.local.
//
// Master = `dev-env.local` (gitignored, the source of truth). Sectioned .env format,
// tolerant of both `KEY=value` and `export KEY=value`:
//
//   [shared]                       # optional — merged into every target (target wins on conflict)
//   POSTGRES_URL=postgres://...
//   [apps/partner/.env.local]      # section name = repo-relative target path
//   export MOLLIE_CLIENT_ID=...
//
// Modes:
//   --seed     read each target's .env + .env.local (merged; .env.local wins) and write the
//              master (one section per target) + dev-env.example (committed, values blanked).
//   --check    list targets whose on-disk file is missing/empty; exit 1 if any. Writes nothing.
//   (default)  render any MISSING/EMPTY target from the master (won't clobber a populated file).
//   --force    render ALL targets from the master (overwrite).
//
// Rendered files use `export ` prefixes (work under `source` AND Next's dotenv loader).
// NEVER prints secret values — only key names, paths, and counts.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { join, dirname } from 'path';

const REPO = (() => {
  try { return execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim(); }
  catch { return process.cwd(); }
})();
const MASTER = join(REPO, 'dev-env.local');
const EXAMPLE = join(REPO, 'dev-env.example');

// Targets the master manages (output order).
const TARGETS = [
  'apps/admin/.env.local',
  'apps/user/.env.local',
  'apps/partner/.env.local',
  'packages/data/.env.local',
];

const GEN_HEADER =
  '# Generated by scripts/apply-dev-env.mjs from dev-env.local.\n' +
  '# Do not edit here — edit the master, then re-run: node scripts/apply-dev-env.mjs --force\n\n';

const ENV_LINE = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/;

// Ordered [key, value] pairs from a .env-ish file (handles `export` prefix). Missing -> [].
function parseEnvFile(path) {
  if (!existsSync(path)) return [];
  const out = [];
  for (const raw of readFileSync(path, 'utf8').split('\n')) {
    const line = raw.replace(/\r$/, '');
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const m = line.match(ENV_LINE);
    if (m) out.push([m[1], m[2]]);
  }
  return out;
}

// Parse the sectioned master -> { shared: [[k,v]], targets: { path: [[k,v]] } }.
function parseMaster(path) {
  const shared = [];
  const targets = {};
  let cur = null;
  for (const raw of readFileSync(path, 'utf8').split('\n')) {
    const line = raw.replace(/\r$/, '');
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const sec = t.match(/^\[(.+)\]$/);
    if (sec) {
      const name = sec[1].trim();
      if (name === 'shared') cur = shared;
      else { targets[name] = targets[name] || []; cur = targets[name]; }
      continue;
    }
    const m = line.match(ENV_LINE);
    if (m && cur) cur.push([m[1], m[2]]);
  }
  return { shared, targets };
}

// Last value wins, preserving last-seen order.
function dedupeLast(pairs) {
  const map = new Map();
  for (const [k, v] of pairs) map.set(k, v);
  return [...map.entries()];
}

function targetIsEmpty(relPath) {
  return parseEnvFile(join(REPO, relPath)).length === 0; // missing or no keys
}

// ---- modes ----

function seed() {
  const head = [
    '# dev-env.local — local-dev master (gitignored). Single source of truth for .env.local files.',
    '# Apply:   node scripts/apply-dev-env.mjs [--force]',
    '# Re-seed: node scripts/apply-dev-env.mjs --seed',
    '',
  ];
  const real = [...head];
  const example = [...head];
  for (const t of TARGETS) {
    const dir = join(REPO, dirname(t));
    const merged = dedupeLast([
      ...parseEnvFile(join(dir, '.env')), // base
      ...parseEnvFile(join(REPO, t)),     // .env.local overrides
    ]);
    real.push(`[${t}]`);
    example.push(`[${t}]`);
    for (const [k, v] of merged) { real.push(`${k}=${v}`); example.push(`${k}=`); }
    real.push('');
    example.push('');
  }
  writeFileSync(MASTER, real.join('\n'));
  writeFileSync(EXAMPLE, example.join('\n'));
  const parsed = parseMaster(MASTER);
  console.log(`Wrote master -> ${MASTER}`);
  console.log(`Wrote template -> ${EXAMPLE}`);
  for (const t of TARGETS) console.log(`  [${t}] ${(parsed.targets[t] || []).length} keys`);
}

function check() {
  let missing = 0;
  for (const t of TARGETS) {
    const empty = targetIsEmpty(t);
    if (empty) missing++;
    console.log(`${empty ? 'NEEDS' : 'ok   '}  ${t}`);
  }
  if (missing) {
    console.log(`\n${missing} target(s) missing/empty — run: node scripts/apply-dev-env.mjs`);
    process.exit(1);
  }
  console.log('\nall targets present');
}

function apply(force) {
  if (!existsSync(MASTER)) {
    console.error(`No master at ${MASTER}. Distribute it (out-of-band) or run --seed.`);
    process.exit(1);
  }
  const { shared, targets } = parseMaster(MASTER);
  let wrote = 0;
  for (const t of TARGETS) {
    const tv = targets[t] || [];
    if (!force && !targetIsEmpty(t)) { console.log(`skip   ${t} (present)`); continue; }
    if (tv.length === 0 && shared.length === 0) { console.log(`skip   ${t} (not in master)`); continue; }
    const merged = dedupeLast([...shared, ...tv]); // target overrides shared
    writeFileSync(join(REPO, t), GEN_HEADER + merged.map(([k, v]) => `export ${k}=${v}`).join('\n') + '\n');
    console.log(`wrote  ${t} (${merged.length} keys)`);
    wrote++;
  }
  console.log(`\n${wrote} file(s) written.`);
}

const args = process.argv.slice(2);
if (args.includes('--seed')) seed();
else if (args.includes('--check')) check();
else apply(args.includes('--force'));
