import type { Metadata } from "next"
import localFont from "next/font/local"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import App from './app'
import NextAuthProvider from './nextauth'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextAuthProvider> 
          <AppRouterCacheProvider>
            <App>
              {children}
            </App>
          </AppRouterCacheProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
