import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import localFont from 'next/font/local'
import App from './app'
import NextAuthProvider from './nextauth'
import StoreProvider from './StoreProvider'
import './globals.css'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <StoreProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <NextAuthProvider>
            <NextIntlClientProvider messages={messages}>
              <App>
                {children}
              </App>
            </NextIntlClientProvider>
          </NextAuthProvider>
        </body>
      </StoreProvider>
    </html>
  )
}
