import { getBusinessEntity } from '@repo/data/business-entity'

export default async function VerifactuNoticePage() {
  const co = await getBusinessEntity()

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-12 text-sm text-gray-700 leading-relaxed">

        <h1 className="text-2xl font-bold text-gray-900 mb-1">Veri*factu Compliance Notice for Spanish Partners</h1>
        <p className="text-xs text-gray-400 mb-8">Sunbnb Partner Programme &middot; Effective: 7 March 2026</p>

        <section className="mb-8 bg-amber-50 border border-amber-200 rounded-lg p-5">
          <h2 className="text-base font-semibold text-gray-900 mb-2">Important: Spanish Tax Mandate — Veri*factu (January 2026)</h2>
          <p>
            The Kingdom of Spain has enacted <strong>Real Decreto 1007/2023</strong>, establishing the <strong>Veri*factu</strong> system as the mandatory framework for electronic invoicing and receipt generation for all businesses operating within Spanish territory. Compliance became obligatory from <strong>1 January 2026</strong>.
          </p>
          <p className="mt-2">
            As your Beach Club is the <strong>Seller of Record</strong> for all customer transactions processed through Sunbnb, these obligations apply directly to your business.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-base font-semibold text-gray-900 mb-2">What Is Veri*factu?</h2>
          <p>
            Veri*factu (&ldquo;Verified Invoicing&rdquo;) is a system mandated by the Spanish Tax Agency (Agencia Tributaria — AEAT) that requires all commercial invoices and simplified receipts to:
          </p>
          <ul className="mt-2 list-disc list-inside text-gray-600 space-y-1.5">
            <li>Be generated by <strong>certified software</strong> (software de facturación homologado)</li>
            <li>Include a <strong>QR code</strong> linking to the AEAT verification portal</li>
            <li>Implement <strong>cryptographic chaining</strong> (encadenamiento criptográfico) — each receipt is cryptographically linked to the previous one, making retroactive tampering detectable</li>
            <li>Be transmitted to AEAT either in <strong>real-time or near-real-time</strong>, or be available for immediate verification via the QR code</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-base font-semibold text-gray-900 mb-2">How Sunbnb Supports Your Compliance</h2>
          <p>
            The Sunbnb platform generates <strong>Veri*factu-compliant receipts</strong> for all transactions occurring at Spanish partner venues. Our system implements:
          </p>
          <div className="mt-3 space-y-3">
            <div className="flex items-start gap-3 bg-gray-50 rounded-lg p-3 border border-gray-100">
              <span className="mt-0.5 w-6 h-6 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">✓</span>
              <div>
                <p className="font-medium text-gray-900">Mandatory QR Codes</p>
                <p className="text-gray-500">Every receipt includes a QR code formatted per AEAT specifications, enabling customers and tax inspectors to verify the receipt against the tax agency&rsquo;s records.</p>
              </div>
            </div>
            <div className="flex items-start gap-3 bg-gray-50 rounded-lg p-3 border border-gray-100">
              <span className="mt-0.5 w-6 h-6 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">✓</span>
              <div>
                <p className="font-medium text-gray-900">Cryptographic Chaining</p>
                <p className="text-gray-500">Each receipt includes a hash of the preceding receipt, forming an immutable chain. This satisfies the anti-tampering requirements of RD 1007/2023 and prevents undetected modification or deletion of records.</p>
              </div>
            </div>
            <div className="flex items-start gap-3 bg-gray-50 rounded-lg p-3 border border-gray-100">
              <span className="mt-0.5 w-6 h-6 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">✓</span>
              <div>
                <p className="font-medium text-gray-900">Mandatory Receipt Fields</p>
                <p className="text-gray-500">All receipts include: issuer NIF/CIF, recipient details (where required), itemised services with applicable IVA rates, receipt number, date/time, and the Veri*factu-compliant QR code.</p>
              </div>
            </div>
            <div className="flex items-start gap-3 bg-gray-50 rounded-lg p-3 border border-gray-100">
              <span className="mt-0.5 w-6 h-6 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">✓</span>
              <div>
                <p className="font-medium text-gray-900">Record Retention</p>
                <p className="text-gray-500">Transaction records are retained for the legally required period and are exportable at any time from your partner dashboard for your own accounting and tax filing purposes.</p>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-base font-semibold text-gray-900 mb-2">Your Obligations</h2>
          <p>
            While Sunbnb automates the receipt generation process, the <strong>legal responsibility for tax compliance rests with you</strong> as the Seller of Record. You are responsible for:
          </p>
          <ul className="mt-2 list-disc list-inside text-gray-600 space-y-1.5">
            <li>Ensuring your NIF/CIF and business details are accurate in the Sunbnb partner dashboard</li>
            <li>Declaring and remitting IVA to the Agencia Tributaria</li>
            <li>Keeping your own copies of all receipts for the statutory retention period</li>
            <li>Consulting with your tax advisor regarding your specific obligations under Spanish tax law</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-base font-semibold text-gray-900 mb-2">Disclaimer</h2>
          <p>
            {co.companyName} provides the Veri*factu-compliant receipt generation feature as a technology service to assist partners in meeting their regulatory obligations. This does not constitute tax advice. {co.companyName} expressly disclaims liability for any tax penalties, interest, or sanctions arising from a partner&rsquo;s failure to comply with Spanish tax law. Partners are strongly advised to engage a qualified Spanish tax professional (asesor fiscal) for guidance on their specific obligations.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">Contact</h2>
          <ul className="space-y-1 text-gray-600">
            <li><strong>{co.companyName}</strong></li>
            {co.companyAddress && <li>{co.companyAddress}</li>}
            {(co.businessId || co.vatId) && (
              <li>
                {co.businessId ? `Business ID: ${co.businessId}` : ''}
                {co.businessId && co.vatId ? ' · ' : ''}
                {co.vatId ? `VAT: ${co.vatId}` : ''}
              </li>
            )}
            {co.contactEmail && <li>Email: {co.contactEmail}</li>}
            {co.contactPhone && <li>Phone: {co.contactPhone}</li>}
          </ul>
        </section>

      </div>
    </div>
  )
}
